################################################################################
#                Drop Configuration - penalty level, autoloot...               #
################################################################################

# Sorry, these are korean formulas coefficients, it will be a bit complicated...

# Level difference, on which level difference penalty will be enabled
#
# Default: 5
drop.minLevelDifferenceForPenalty: 5

# Chance of level penalty applied per level.
# This means for every level of levelDifference greater than minLevelDifferenceForPenalty
# there will be chance 0.18 that drop will not happen
# Default: 0.18
drop.levelPenaltyBaseValue: 0.18

# Level difference, on which level difference penalty chance wil stop multiplying.
# This means that level drop penalty will be
# multiplied on maxLevelDifferenceForPenalty - minLevelDifferenceForPenalty even
# if level difference is greater
#
# For example, if minLevelDifference is 5 and maxLevelDifference is 10,
# penalty chance will be 0.90, even if levelDifference is greater than 10
#
# Default: 10
drop.maxLevelDifferenceForPenalty: 10
